CC = g++
FLAGS = -g -Wall -Wextra -pedantic --std=c++14 #-Werror

r: 	tp3
	./tp3

tp3:	tp3.cpp
	$(CC) $(FLAGS) tp3.cpp -o tp3 
tp1:	tp1.cpp
	$(CC) $(FLAGS) tp1.cpp -o tp1 

tp2:	tp2.cpp
	$(CC) $(FLAGS) tp2.cpp -o tp2
clean:
	rm tp1 tp2 
