inftest : InferenceTest.ml Inference.ml
	ocamlc Inference.ml InferenceTest.ml -o inftest


infer : Inference.ml
	ocamlc Inference.ml -o infer

types : types.ml
	ocamlc types.ml -o types

arbres : arbres.ml
	ocamlc arbres.ml -o arbres
r : arbres 
	./arbres
