<definitions
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:tns="urn:exemple"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    targetNamespace="urn:exemple"
    name="exempleService">


  <message name="retourDateRequest">
    <part name="requete" type="xsd:string"> </part>
  </message>
  
  <message name="retourDateResponse">
    <part name="retourDateReturn" type="xsd:string"> </part>
  </message>

  <!-- les messages peuvent etre définis ici -->
  <portType name="essai_instancePortType">
    <!-- Nom de l'opération -->
    <operation name="date">
      
      <!-- Message associé à la requête-->
      <input message="tns:retourDateRequest"></input>

      <!-- Message rendu en tant que réponse -->
      <output message="tns:retourDateReturn"></output>
    </operation>
  </portType>

  <binding name="essai_instanceBinding"
	   type="tsn:RetourDateRequest">
    
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"
		  style="rpc"></soap:binding>

    <operation name="date">
      <soap:operation soapAction="date"> </soap:operation>
      <input>
	<soap:body use="literal" namespace="tp.serviceweb"> </soap:body>
      </input>
      <output>
	<soap:body use="literal" namespace="tp.serviceweb"> </soap:body>
      </output>
    </operation>
  </binding>

  <service name="exempleService">
    <port>
      <soap:address location="http://localhost:8080/lastexo.php">
      </soap:address> 
    </port>
  </service>
</definitions>